### ISSUE TITLE
palette.refresh() crashes

### ISSUE THREAD

**Issue by acarreras** [federico-pepe/nice-color-palettes#1]
Hi,
Usefull library! Congrats!
The palette.refresh(); command makes the P5 sketch chrash.
It returns a 403 HTTP error.
By the other hand accessing with the web browser the api adress to refresh the palletes works ok for me.
http://www.colourlovers.com/api/palettes/top?format=json&numResults=100
I don't know what to check more.
It would be nice If you can check it.
Best,
Anna

**Comment by federico-pepe** [comment]
Hi @acarreras, thank you for getting in touch and for finding my library useful. I think that the website is blocking connection coming from java. I’m working on a solution and will update the library as soon as possible
