### ISSUE TITLE
Need the NiceColorPalettes.jar library inside the /library folder

### ISSUE THREAD

**Issue by acarreras** [federico-pepe/nice-color-palettes#3]
You fixed the issue with the 403 http error super fast!
For the users to be able to use the fixed library a NiceColorPalettes.jar file should be inside the /library folder. Without the compiled version no one can use the new fixed library and is still getting the error.
Best,

**Comment by federico-pepe** [comment]
Hi @acarreras and thanks for telling me this. I'm checking with the Processing's team that deal with the contribution manager if I did some mistakes because it looks like the contribution manager doesn't see the update in my code. I'll let you know as soon as I manage to fix this problem.

**Comment by federico-pepe** [comment]
@acarreras this should be fixed now. Can you please check and let me know?

**Comment by acarreras** [comment]
Solved! Processing Library Manager works fine to update your library. And everything works great!
