### ISSUE TITLE
Refreshing not working correctly

### ISSUE THREAD

**Issue by federico-pepe** [federico-pepe/nice-color-palettes#4]
When refreshing palettes, it always return 20 results.

**Comment by pawal** [comment]
I get a 403 error when refreshing the palettes now.

**Comment by federico-pepe** [comment]
Hi @pawal. I think colorlover succeeds in blocking requests from my library (copying and pasting into the browser the request url works perfectly). Unfortunately right now I don't have all the tools installed on my computer to do the tests and update the library, can you work with the colors already inside?

**Comment by pawal** [comment]
Absolutely, just wanted to give a heads up.
Perhaps the solution is to set the same headers as any webbrowser would do.

**Comment by federico-pepe** [comment]
That's exactly how I fixed it the first time. I'll try to have a look as soon as possible
